### ISSUE TITLE
openscad-mdimggen:   NameError: name 'platform' not defined?

### ISSUE THREAD

**Issue by RAMilewski** [revarbat/openscad_docsgen#21]
When I try to run openscad-mdimggen on my local BOSL2 tutorials it fails with a NameError:

Traceback (most recent call last):
  File "/usr/local/bin/openscad-mdimggen", line 8, in <module>
    sys.exit(mdimggen_main())
  File "/usr/local/lib/python3.9/site-packages/openscad_docsgen/mdimggen.py", line 163, in mdimggen_main
    elif platform.system() == 'Windows':
NameError: name 'platform' is not defined

openscad_mdimggen_rc is unmodified.

Running Python 3.9.1 on MacOS 10.14.6

**Comment by revarbat** [comment]
Should be fixed in v2.0.35
