### ISSUE TITLE
openscad-mdimggen fails with     AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

### ISSUE THREAD

**Issue by RAMilewski** [revarbat/openscad_docsgen#23]
Apparently ANTIALIAS was removed in PILLOW 10.0.0

Attempting to process BOSL2 Tutorials locally....

```
RAM@Maxwell BOSL2 % openscad-mdimggen
BOSL2.wiki/Tutorial-Shapes2d.md
  Shapes2d_1.png... Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/openscad-mdimggen", line 8, in <module>
    sys.exit(mdimggen_main())
             ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openscad_docsgen/mdimggen.py", line 173, in mdimggen_main
    mdimggen.processFiles(args.srcfiles)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openscad_docsgen/mdimggen.py", line 121, in processFiles
    image_manager.process_requests(test_only=opts.test_only)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openscad_docsgen/imagemanager.py", line 173, in process_requests
    self.process_request(req)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openscad_docsgen/imagemanager.py", line 221, in process_request
    osc.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openscad_runner/__init__.py", line 306, in run
    im.thumbnail(self.imgsize, Image.ANTIALIAS)
                               ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

**Comment by RAMilewski** [comment]
Appears to be fixed.
